export const FIELD_CONFIG = {
  COUNT: 26,
  SEED: 20260824,
  SIZE_MIN: 7,
  SIZE_MAX: 17,
  ALPHA_MIN: 0.05,
  ALPHA_MAX: 0.13,
  SPEED_MIN: 4,
  SPEED_MAX: 11,
  SPIN_MAX: 0.04,
  LIME_RATIO: 0.35,
  PARALLAX_MAX: 14,
  POINTER_HALF_LIFE_MS: 400,
  DPR_CAP: 2,
} as const

export const LOOP_STAGES = [
  {
    id: 'discover',
    word: 'DISCOVER',
    num: '01',
    title: 'We map every agent you already run',
    text: 'Coding agents, MCP servers, and framework agents — found across the fleet without touching production. Nothing has to change before it\u2019s seen.',
    keywords: ['DISCOVERY', 'MCP SERVERS', 'FRAMEWORKS'],
  },
  {
    id: 'understand',
    word: 'UNDERSTAND',
    num: '02',
    title: 'We trace reach to its blast radius',
    text: 'Identity, model, memory, tools, data. Every agent resolves into one graph, and risk shows as paths — not isolated findings.',
    keywords: ['CONTEXT MAPPING', 'TOXIC PATHS'],
  },
  {
    id: 'govern',
    word: 'GOVERN',
    num: '03',
    title: 'We enforce what agents may reach',
    text: 'Your standards become guardrails every agent must pass — mapped to OWASP\u2019s Agentic Top 10, MITRE ATLAS, and the rest of the framework stack.',
    keywords: ['POLICY GUARDRAILS', 'FRAMEWORK MAPPED'],
  },
  {
    id: 'act',
    word: 'ACT',
    num: '04',
    title: 'We close what matters first',
    text: 'An exposed endpoint, an over-privileged identity, and a regulated data store on one path — prioritized, resolved, with the evidence written by the graph.',
    keywords: ['RISK PRIORITIZATION', 'AUDIT-READY'],
  },
] as const
