export const FIELD_CONFIG = {
  COUNT: 26,
  SEED: 20260824,
  SIZE_MIN: 7,
  SIZE_MAX: 17,
  ALPHA_MIN: 0.05,
  ALPHA_MAX: 0.13,
  SPEED_MIN: 4,
  SPEED_MAX: 11,
  SPIN_MAX: 0.04,
  LIME_RATIO: 0.35,
  PARALLAX_MAX: 14,
  POINTER_HALF_LIFE_MS: 400,
  DPR_CAP: 2,
} as const

export const LOOP_STAGES = [
  {
    id: 'discover',
    word: 'DISCOVER',
    num: '01',
    title: 'We inventory every model you run',
    text: 'We sweep your cloud, code, and contracts to map every AI system your people build, buy, or quietly ship.',
    keywords: ['DISCOVERY'],
  },
  {
    id: 'understand',
    word: 'UNDERSTAND',
    num: '02',
    title: 'We trace risk to its source',
    text: 'We resolve data, permissions, prompts, and vendors into one continuously updated picture of your exposure.',
    keywords: ['CONTEXT MAPPING', 'VENDOR INTELLIGENCE'],
  },
  {
    id: 'govern',
    word: 'GOVERN',
    num: '03',
    title: 'We enforce your standards',
    text: 'We encode your standards as guardrails and enforce them everywhere models appear — before incidents do.',
    keywords: ['POLICY GUARDRAILS'],
  },
  {
    id: 'act',
    word: 'ACT',
    num: '04',
    title: 'We fix what matters first',
    text: 'We resolve findings in priority order. Exposure drops. Audit evidence writes itself.',
    keywords: ['RISK PRIORITIZATION', 'CONTINUOUS AUDIT'],
  },
] as const
