export const FIELD_CONFIG = {
  COUNT: 26,
  SEED: 20260824,
  SIZE_MIN: 7,
  SIZE_MAX: 17,
  ALPHA_MIN: 0.05,
  ALPHA_MAX: 0.13,
  SPEED_MIN: 4,
  SPEED_MAX: 11,
  SPIN_MAX: 0.04,
  LIME_RATIO: 0.35,
  PARALLAX_MAX: 14,
  POINTER_HALF_LIFE_MS: 400,
  DPR_CAP: 2,
} as const

export const ORB_CONFIG = {
  COUNT: 380,
  SEED: 95255,
  RADIUS_MARGIN: 8,
  RADIAL_SPEED_MIN: 12,
  RADIAL_SPEED_MAX: 26,
  ANGULAR_SPEED_MAX: 0.22,
  DOT_SIZE_MIN: 0.8,
  DOT_SIZE_MAX: 2.0,
  ALPHA_EDGE: 0.07,
  ALPHA_CORE: 0.85,
  CORE_RATIO: 0.16,
  PAPER_RATIO: 0.28,
  BREATH_AMP: 0.015,
  BREATH_SPEED: 0.42,
  POINTER_TILT_MAX: 10,
  POINTER_HALF_LIFE_MS: 300,
  RESPAWN_BAND: 0.16,
  DPR_CAP: 2,
} as const

export const LOOP_STAGES = [
  {
    id: 'discover',
    word: 'DISCOVER',
    num: '01',
    title: 'See every model you run',
    text: 'Axon sweeps your cloud, code, and contracts to inventory every AI system your teams build, buy, or quietly ship.',
  },
  {
    id: 'understand',
    word: 'UNDERSTAND',
    num: '02',
    title: 'Trace risk to its source',
    text: 'Data, permissions, prompts, and vendors resolve into one continuously updated picture of exposure.',
  },
  {
    id: 'govern',
    word: 'GOVERN',
    num: '03',
    title: 'Set policy once',
    text: 'Guardrails encode your standards and enforce them everywhere models appear — before incidents do.',
  },
  {
    id: 'act',
    word: 'ACT',
    num: '04',
    title: 'Fix what matters first',
    text: 'Prioritized findings route straight to owners. Exposure drops. Audit evidence writes itself.',
  },
] as const
